## import packages

In [2]:
import tensorflow as tf
import numpy as np

C:\Users\Iman\Anaconda3\envs\TENS\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Iman\Anaconda3\envs\TENS\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Iman\Anaconda3\envs\TENS\lib\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Iman\Anaconda3\envs\TENS\lib\site-packages\tensorflow\python\framework

In [11]:
import numpy as np
x = np.array([
    [ 1,    3, 0.13,  27],
    [ 9, -2.5,  3.6,  -1],
    [ 4,    0,    5,   6],
    [15,    1,    2,   3]]).reshape((1, 4, 4, 1))
x

array([[[[ 1.  ],
         [ 3.  ],
         [ 0.13],
         [27.  ]],

        [[ 9.  ],
         [-2.5 ],
         [ 3.6 ],
         [-1.  ]],

        [[ 4.  ],
         [ 0.  ],
         [ 5.  ],
         [ 6.  ]],

        [[15.  ],
         [ 1.  ],
         [ 2.  ],
         [ 3.  ]]]])

* tf.nn.conv2d()
* tf.nn.max_pool

## Build convolution algorithm

In [1]:

x = np.array([
    [ 1,    3, 0.13,  27],
    [ 9, -2.5,  3.6,  -1],
    [ 4,    0,    5,   6],
    [15,    1,    2,   3]]), dtype=np.float32).reshape((1, 4, 4, 1))

print(x)
X = tf.constant(x)


def conv2d(input):
    F_W = tf.Variable(tf.truncated_normal((2, 2, 1, 3)))#random distribution
    F_b = tf.Variable(tf.zeros(3))
    strides = [1, 2, 2, 1]
    padding = 'VALID' #same
    return tf.nn.conv2d(input, F_W, strides, padding) + F_b

out = conv2d(X)
print(out)

NameError: name 'np' is not defined

## pool operations

In [3]:

x = np.array([
    [0,   1, 0.5,  10],
    [2, 2.5,   1,  -8],
    [4,   0,   5,   6],
    [15,  1,   2,   3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)

def maxpool(input):
    ksize = [1, 2, 2, 1]
    strides = [1, 1, 1, 1]
    padding = 'SAME'
    return tf.nn.max_pool(input, ksize, strides, padding)

with tf.Session() as sess:
    output = sess.run(maxpool(x))
    print(output.shape)
    print(output)

#return output
#out = maxpool(X)
#print(out)

(1, 4, 4, 1)
[[[[ 2.5]
   [ 2.5]
   [10. ]
   [10. ]]

  [[ 4. ]
   [ 5. ]
   [ 6. ]
   [ 6. ]]

  [[15. ]
   [ 5. ]
   [ 6. ]
   [ 6. ]]

  [[15. ]
   [ 2. ]
   [ 3. ]
   [ 3. ]]]]


## Merged

In [4]:

data = np.array([
    [   1,    3, 0.13,  27],
    [   9, -2.5,  3.6,  -1],
    [11.3,    2, -5.1,   0],
    [  -2,    1,    2,   5]], dtype=np.float32).reshape((2, 2, 2, 2))

def conv2d(input):
    x = tf.placeholder(tf.float32,[None,2,2,2])
    F_W = tf.Variable(tf.truncated_normal((1, 1, 2, 3)))
    F_b = tf.Variable(tf.zeros(3))
    strides = [1, 2, 2, 1]
    padding = 'VALID'
    conv_calc = tf.nn.conv2d(x, F_W, strides, padding)# + F_b
    print(conv_calc)
    
    ksize_pool = [1, 2, 2, 1]
    strides_pool = [1, 2, 2, 1]
    padding_pool = 'SAME'
    pool = tf.nn.max_pool(conv_calc, ksize_pool, strides_pool, padding_pool)
    
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        output = sess.run(pool, feed_dict={x:input})
        print(output.shape)
        print(output)
    return output

output_conv = conv2d(data)
print("\n***********************\n")

Tensor("Conv2D_1:0", shape=(?, 1, 1, 3), dtype=float32)
(2, 1, 1, 3)
[[[[-3.7744648e+00  2.3894091e+00  1.5363035e+00]]]


 [[[-1.5852066e+01 -5.0478430e+00  7.1458817e-03]]]]

***********************

